name = "movies-api"
type = "webpack"
route = "movies-api.chapmanio.dev/*"
account_id = "f90442acc75d6de465cf6c13b2f2b810"
zone_id = "2fd9107fc647d965a1ae1985ca82731c"
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-07"
webpack_config = "webpack.config.js"

# [secrets]
# DATABASE_URL
# COOKIE_DOMAIN
# MOVIE_API_KEY
# JWT_SECRET
